booktime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main.admin import main_admin, central_office_admin, dispatchers_admin

urlpatterns = [
    path('admin/', main_admin.urls),
    path('office-admin/', central_office_admin.urls),
    path('dispatch-admin/', dispatchers_admin.urls),
    #path('admin/', include(admin_url)),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('main.urls', namespace='main'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

main/urls.py
import rest_framework
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import DetailView, TemplateView
from rest_framework import routers
from rest_framework.authtoken import views as authtoken_views
from rest_framework.authtoken.views import obtain_auth_token

from . import admin, endpoints, views
from .forms import LoginForm
from .models import Product
from .views import ContactUs, Product_list, SignUpView

app_name = 'main'

router = routers.DefaultRouter()
router.register(r'orderlines', endpoints.PaidOrderLineViewSet)
router.register(r'orders', endpoints.PaidOrderViewSet)
urlpatterns = [
    

    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('about-us/', TemplateView.as_view(template_name='aboutus.html'), name='about-us' ),
    path('contact-us/', ContactUs.as_view(), name='contact_us'),
    path('products/<slug:tag>/', Product_list.as_view(), name='products'),
    path('product/<slug:slug>/', DetailView.as_view(model=Product), name="product"),
    path('login/', auth_views.LoginView.as_view(template_name='main/loginv2.html', form_class=LoginForm), name="login"),
    path('signup/', SignUpView.as_view(), name="signup"),
    path('address-list/', views.AddressListView.as_view(), name='address_list'),
    path('address/create/', views.AddressCreateView.as_view(), name='address_create'),
    path('address/<int:pk>/update/', views.AddressUpdateView.as_view(), name="address_update"),
    path('address/<int:pk>/delete/', views.AddressDeleteView.as_view(), name='address_delete'),
    path('add_to_basket/', views.add_to_basket, name="add_to_basket"),
    path('manage_basket/', views.manage_basket, name='manage_basket'),
    path('address/select', views.AddressSelectionView.as_view(), name='address_select'),
    path('order/done/', TemplateView.as_view(template_name='main/order_done.html'), name='checkout_done'),
    path('order/dashboard/', views.OrderView.as_view(), name="order_dashboard"),
    path("customer-service/<int:order_id>/", views.room, name="cs-chatroom"),
    path("customer-service/", TemplateView.as_view(template_name="customer-service.html"), name="cs_main"),
    path('api/', include(router.urls)),
    path("mobile-api/auth/", authtoken_views.obtain_auth_token, name="mobile_token"),
    path("mobile-api/my-orders/", endpoints.my_orders, name="mobile_my_orders"),
]

main/forms.py
from django import forms
from django.core.mail import send_mail
import logging
from django.contrib.auth.forms import UserCreationForm as DjangoUserCreationForm
from django.contrib.auth.forms import UsernameField
from . import models
from django.contrib.auth import authenticate
from django.forms import inlineformset_factory
from . import widgets, models
logger = logging.getLogger(__name__) 
class ContactForm(forms.Form):
    name = forms.CharField(label='your name', max_length=100)
    message = forms.CharField(max_length=400, widget=forms.Textarea)
    def send_mail(self):
        send_mail('Site Message', self.cleaned_data['message'], 'site@domain.com', ['customer@domain.com'], fail_silenty=False)
    
class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields= ['email']
        field_classes = {'email': UsernameField}
    def send_mail(self):
        logger.info('sending welcome email  to {} upon signup '.format(self.cleaned_data['email']))
        send_mail('welcome {}'.format(self.cleaned_data['email']), 'message', 'eng_mustafa_yossef@hotmai.com', [self.cleaned_data['email'],], fail_silently=False)
class LoginForm(forms.Form):
    email = forms.EmailField(label='email address')
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user  = None
        return super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        if email is not None and password:
            self.user = authenticate(self.request,
            email=email,
            password=password)
        if self.user is None:
            raise forms.ValidationError("Invalid email/password combination.")
        logger.info("Authentication successful for email=%s", email)
        return self.cleaned_data
    def get_user(self):
        return self.user
BasketLineForm = inlineformset_factory(models.Basket, models.BasketLine, fields=('quantity',), extra=0, widgets={'quantity': widgets.PlusMinusNumberInput()})
class AddressSelectionForm(forms.Form):
    billing_address = forms.ModelChoiceField(queryset=None, help_text='bill')
    shipping_address  = forms.ModelChoiceField(queryset=None)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset = models.Address.objects.filter(user=user)
        self.fields['billing_address'].queryset = queryset
        self.fields['shipping_address'].queryset = queryset
class AddressCreateForm(forms.ModelForm):
    class Meta:
        model = models.Address
        exclude = ['user',]        

main/views.py
from django.shortcuts import render
from django.views.generic import FormView
from .forms import  ContactForm, BasketLineForm, AddressSelectionForm, AddressCreateForm
from django.views.generic import ListView, DetailView
from .models import Product, ProductTag, Address, Basket, BasketLine
from django.shortcuts import get_object_or_404
from .forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse,reverse_lazy
from . import models
from django.http import HttpResponseRedirect
import logging
from django import forms as django_forms
from django.db import models as django_models
import django_filters
from django_filters.views import FilterView 
# Create your views here.
logger = logging.getLogger(__name__) 

class ContactUs(FormView):
    form_class = ContactForm
    template_name = 'contact-us.html'
    success_url = '/'
    
    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

class Product_list(ListView):

    model = Product
    context_object_name = 'product_list'
    template_name='main/product_list.html'
    paginate_by = 4
    def get_queryset(self):
        tag = self.kwargs.get('tag')
        if tag != 'all':
            self.tag = get_object_or_404(ProductTag, slug=tag)
            if self.tag:
                products = Product.objects.active().filter(tags=self.tag)
        else:
            products = Product.objects.active() 
        return products.order_by('name')       
class SignUpView(FormView):
    template_name = 'main/signup.html'
    form_class = UserCreationForm

    def get_success_url(self):
        response = self.request.GET.get('next', '/')
        return response
    def form_valid(self, form):
        form.save()
        email = form.cleaned_data['email']
        raw_password = form.cleaned_data['password1']
        user = authenticate(email=email, password=raw_password)
        if user:
            login(self.request, user)
            form.send_mail()
            messages.info(self.request, 'you successfully become a user')
        return super().form_valid(form)
class AddressListView(LoginRequiredMixin, ListView):
    model = Address
    template_name='main/addres_list.html'
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)
class AddressCreateView(LoginRequiredMixin, CreateView):
    model = Address
    form_class = AddressCreateForm
    success_url = reverse_lazy('main:address_list')
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)
class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model = Address
    fields = ['country', 'address1', 'address2', 'zip_code']

    success_url = reverse_lazy('main:address_list')
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)
class AddressDeleteView(LoginRequiredMixin, DeleteView):
    model = Address
    success_url = reverse_lazy('main:address_list')
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


def add_to_basket(request):
    if request.method == 'GET':
        product  = get_object_or_404(Product, pk=request.GET.get('product_id'))
        logger.info('get product')
        print(product.name)
        basket = request.basket
        logger.info('get basket ')
        if not request.basket:
            if request.user.is_authenticated:
                user = request.user

            else:
                user = None
            basket = models.Basket.objects.create(user=user)
            request.session['basket_id'] = basket.id
        basketline, created = models.BasketLine.objects.get_or_create(basket=basket, product=product)
        if not created:
            basketline.quantity += 1
            basketline.save()
            logger.info('basketline quantity')
        return HttpResponseRedirect(reverse('main:product', kwargs={'slug':product.slug}))    

def manage_basket(request):
    if not request.basket:
        return render(request, 'main/basket.html', {'formset': None})
    if request.method == 'POST':
        formset = BasketLineForm(request.POST, instance=request.basket)
        if formset.is_valid():
            formset.save()
    else:
        formset = BasketLineForm(instance=request.basket)
    if request.basket.is_empty():
        return render(request, 'main/basket.html', {'formset': None})
    return render(request, 'main/basket.html', {'formset': formset})                    
class AddressSelectionView(FormView):
    template_name = 'main/address_select.html'
    form_class = AddressSelectionForm
    success_url = reverse_lazy('main:checkout_done')
    def get_form_kwargs(self):
        kwargs =  super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    def form_valid(self, form):
        del self.request.session['basket_id']
        basket = self.request.basket
        basket.create_order(form.cleaned_data['billing_address'], form.cleaned_data['shipping_address'])
        return super().form_valid(form)
class DateInput(django_forms.DateInput):
    input_type = 'date'
class OrderFilter(django_filters.FilterSet):
    class Meta:
        model = models.Order
        fields = {
            'user__email': ['icontains'],
            'status': ['exact'],
            'date_added': ['lt', 'gt'],
            'date_updated': ['lt', 'gt'],
        }
        filter_overrides = {
            django_models.DateTimeField: {
                'filter_class': django_filters.DateFilter,
                'extra': lambda f:{'widget': DateInput}}}
class OrderView(UserPassesTestMixin, FilterView):
    filterset_class = OrderFilter
    login_url = reverse_lazy("main:login")
    def test_func(self):
        return self.request.user.is_staff is True   
def room(request, order_id):
    return render(request, "chat_room.html", {"room_name_json": str(order_id)})

main/templates/main/address_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form method="POST">
      <p>
          are you sure you want to delete this address?
      </p>
      <button type="submit" class="btn btn-danger" >delete</button>
  </form>
{% endblock content %}

main/templates/main/address_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h3>please fil in the form if you want to create an address</h3>
  <form method="POST" >
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-primary">Create address</button>    
  </form>
{% endblock content %}

main/templates/main/address_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid">
    {% for address in object_list  %}
      <div class="raw">
          <p>
              {{address.user.email}}<br>
              {{address.address1}}<br>
              {{address.country}}<br>
              <p>
              <a href="{% url "main:address_update" address.id %}" class="btn btn-warning"  >Update address</a>
              <a href="{% url "main:address_delete" address.id %}" class="btn btn-danger"  >Update address</a>
              </p>  
          </p>
          
      </div>
      {% empty %}
      <p>no addresses yet</p>
      {% if not forloop.last %}
        <hr>
      {% endif %}
      {% if forloop.last %}
        <a href="{% url 'main:address_create' %}">create address</a>
      {% endif %}
    {% endfor %}
  </div>
{% endblock content %}

main/templates/main/address_select.html
{% extends "base.html" %}

{% block content %}
  <h2>
      select the billing and shipping addresses
  </h2>
  <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-info">submit</button>
      <a href="{% url "main:address_create" %}" class="btn btn-block">create an address</a>
  </form>
{% endblock content %}

main/templates/main/address_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h3>please fil in the form if you want to update an address</h3>
  <form method="POST" >
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">update address</button>    
  </form>
{% endblock content %}

main/templates/main/basket.html
{% extends "base.html" %}
{% block content %}
<h2>Basket</h2>
{% if formset %}
<p>You can adjust the quantities below.</p>
<form method="POST">
{% csrf_token %}
{{ formset.management_form }}
{% for form in formset %}
<p>
<h4 style="color: blue">{{ form.instance.product.name }}</h4><br>
<p style="align-content: center; color: red">{{ form }}</p>
</p>
{% endfor %}
<button type="submit" class="btn btn-default">
Update basket</button>
{% if user.is_authenticated %}
<a href="{% url "main:address_select" %}" class="btn btn-primary">Place order</a>
{% else %}
<a href="{% url "signup" %}?next={% url "main:address_select" %}" class="btn btn-primary">Signup</a>
<a href="{% url "login" %}?next={% url "main:address_select" %}" class="btn btn-primary">Login</a>
{% endif %}
</form>
{% else %}
<p>You have no items in the basket.</p>
{% endif %}
{% endblock content %}
{% block js %}
{% if formset %}
    {{ formset.media }}
{% endif %}
{% endblock js %}

main/templates/main/login.html
{% extends "base.html" %}

{% block content %}
  <h2>fill in to login</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
        {{ form.email.label_tag }}
        <input class="form-control"
        type="email"
        id="email_id"
        name="email"
        placeholder="enter ur email"
        value="{{ form.email.value|default:"" }}"/>
         
         {% if form.email.errors %}
             <div>
                 {{ form.email.errors }}
             </div>
         {% endif %}
                
    </div>
    <div class="form-group">
        {{ form.password.label_tag }}
        <input class="form-control"
        type="password"
        id="password_id"
        name="password"
        placeholder="enter ur password"
        value="{{form.password.value|default:""}}"/>
        
        {% if form.password.errors %}
            <div>
                {{ form.password.errors }}
            </div>

        {% endif %}
                
    </div>
    <button type="submit" class="btn btn-light">submit</button>
  </form>
{% endblock content %}

main/templates/main/loginv2.html
{% extends "base.html" %}

{% block content %}
  <h3>please fil in the form below</h3>
  <form method="POST">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% include "includes/field.html" with field=form.email %}
      {% include "includes/field.html" with field=form.password %}
      <button type="submit" class="btn btn-gray">
          login
      </button>
  </form>
{% endblock content %}

main/templates/main/order_done.html
{% extends 'base.html' %}

{% block content %}
<h1>
    checkout done
</h1>
  <p>
      thank you for submitted your order
  </p>
{% endblock content %}

main/templates/main/order_filter.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% block content %}
<h2>Order dashboard</h2>
<form method="get">
{{ filter.form.as_p }}
<input type="submit"/>
</form>
<p>
{% render_table filter.qs %}
</p>
{% endblock content %}

main/templates/main/product_detail.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% block content %}
<h1>products</h1>
<table class="table">
<tr>
<th>Name</th>
<td>{{ object.name }}</td>
</tr>
<tr>
<th>Cover images</th>
<td>
<div id="imagebox">
loading...
</div>

</td>
</tr>
<tr>
<th>Price</th>
<td>{{ object.price }}</td>
</tr>
<tr>
<th>Description</th>
<td>{{ object.description|linebreaks }}</td>
</tr>
<tr>
<th>Tags</th>
<td>{{ object.tags.all|join:","|default:"No tags available" }}</td>
</tr>
<tr>
        <th>In stock</th>
        <td>{{ object.in_stock|yesno|capfirst }}</td>
        </tr>
        <tr>
        <th>Updated</th>
        <td>{{ object.date_uploaded|date:"F Y" }}</td>
        </tr>
        </table>
        <a href="{% url 'main:add_to_basket' %}?product_id={{ object.id }}" class="btn btn-dark">add to basket</a>
        {% endblock content %}
 
{% block js %}
{% render_bundle "imageswitcher" js %}
<script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>

<script>

document.addEventListener("DOMContentLoaded", function(event){
var images = [
{% for image in object.productimage_set.all %}
{"image": "{{ image.image.url|safe }}", "thumbnail": "{{ image.thumbnail.url|safe }}"},
{% endfor %}
];
ReactDOM.render(
React.createElement(ImageBox, {images: images, imageStart: images[0]}),document.getElementById("imagebox"));
});
</script>
  
{% endblock js %}

main/templates/main/product_list.html
{% extends "base.html" %}

{% block content %}
  
  <br>
  {% for product in page_obj  %}
     <h2>{{ product.name|capfirst }}</h2>
     <a href="{% url 'main:product' product.slug %}">see it here</a> 
     
     {% if not forloop.last %}
         <hr>
     {% endif %}

     
     {% if forloop.last %}
       <hr>
       <br/>
     {% endif %}
       
  {% endfor %}   
  <nav>
      <ul class="pagination">
          
          {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
          {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">previous</a></li>
          {% endif %}
              
          
          {% for pagenum in page_obj.paginator.page_range %}
          <li class="page-item 
          {% if pagenum == page_obj.number %} 
              active
          {% endif %}
              " ><a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a></li>
              
          {% endfor %}
           
          {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">next</a></li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">next</a></li>
          {% endif %}
      </ul>
  </nav>   
 
{% endblock content %}

main/templates/main/signup.html
{% extends "base.html" %}

{% block content %}
    <h2>
        please fill in the fields to signup
    </h2>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.email.label_tag }}
            <input class="form-control"
            type="email"
            id="email_id"
            name="email"
            placeholder="enter your email"
            value="{{form.email.value|default:""}}"/>
            
            {% if form.email.errors %}
                <div>
                    {{ form.email.errors }}    
                </div>
            {% endif %}
                
            </div>
            <div class="form-group">
                {{ form.password1.label_tag }}
                <input class="form-control"
                type="password"
                id="password1_id"
                name="password1"
                placeholder="enter ur password"
                value="{{form.password1.value|default:""}}"/>
                {% if form.password1.errors %}
                <div>
                    {{ form.password1.errors }}    
                </div>
                {% endif %}                
            </div>
        </div>
        <div class="form-group">
            {{ form.password2.label_tag }}
            <input class="form-control"
            type="password"
            id="password2_id"
            name="password2"
            placeholder="confirm password"
            value="{{form.password2.value|default:""}}"/>
            {% if form.password2.errors %}
            <div>
                {{ form.password2.errors }}    
            </div>
            {% endif %}                
        </div>
        <Button type="submit" class="btn btn-primary">submit</Button>            
    </form>
{% endblock content %}